version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1czgynz41yi48"
s3_prefix = "Dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
