name: "Deploy SAM Stack to AWS"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    # Python unit test
    - name: Install Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd S3_Backend/Lambda
        pip install -r "requirements.txt"
        pip install moto boto3
    - name: Unittest Lambda and DynamoDB
      run: | 
         cd S3_Backend/Lambda
         python Lambda/test.py

    # AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: SAM Build
      uses: TractorZoom/sam-cli-action@master
      with:
        sam_command: "build -t template.yaml --debug"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

    - name: SAM Deploy
      uses: TractorZoom/sam-cli-action@master
      with:
        sam_command: deploy -t template.yaml\
          --arn:aws:cloudformation:us-east-1:451545210696:stack/Dev/66fbb160-c755-11ea-adfe-0e3038696552\
          --parameter-overrides ParameterKey=S3BucketName, ParameterKey=DynamoDBTableName \
          --debug \
          --no-fail-on-empty-changeset
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
